compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_config_file: /scratch/max/mlgym/example/cnn_zero_stage_3/ds_config.json
  zero3_init_flag: true
distributed_type: DEEPSPEED
downcast_bf16: "no"
dynamo_backend: "NO"
fsdp_config: {}
machine_rank: 0
main_training_function: main
megatron_lm_config: {}
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
use_cpu: false
gpu_ids: "0,1"

