run_configuration:
  type: train # train, warmstart
  config:
    num_epochs: 10 # Number of epochs
    # num_batches_per_epoch: 100
    gs_config_path: /scratch/max/mlgym/example/cnn_ddp/cnn_experiment_config.yml

environment:
  type: accelerate # multiprocessing,  main_process, accelerate

logging:
  websocket_logging_servers: # List of websocket logging servers, e.g., http://127.0.0.1:9090 http://127.0.0.1:8080
    - http://127.0.0.1:5002
  gs_rest_api_endpoint: http://127.0.0.1:5001 # Endpoint for the grid search API, e.g., http://127.0.0.1:8080
