global_config:
  storage_connector_path: &storage_path_anchor ./file_storage/
  seed: &seed_value 2
  target_key: &target_key_anchor target_key
  model_prediction_key: &model_prediction_key_anchor model_prediction_key
  postprocessing_argmax_key: &postprocessing_argmax_key_anchor postprocessing_argmax_key

dataset_iterators:
  component_type_key: DATASET_ITERATORS
  variant_key: LMWikiBookCorpusDataset
  config:
    dataset_identifier: LMWikiBookCorpus
    dataset_folder_path: /scratch/max/mlgym/example/bert/chunked_tokenized_dataset_train

split_dataset_iterators:
  component_type_key: SPLITTED_DATASET_ITERATORS
  variant_key: RANDOM
  requirements:
    - name: iterators
      component_name: dataset_iterators
      subscription:
        - train
  config:
    split_configs:
      train:
        val: 0.001
        test: 0.001
        train_lm: 0.998
    seed: 2

split_dataset_iterator_2:
  component_type_key: SPLITTED_DATASET_ITERATORS
  variant_key: RANDOM
  requirements:
    - name: iterators
      component_name: split_dataset_iterators
      subscription: [train_lm, val, test]
  config:
    split_configs:
      train_lm:
        rest: 0.999
        train_small: 0.001
    seed: 3

data_collator:
  component_type_key: DATA_COLLATOR
  variant_key: DEFAULT
  config:
    collator_type:
      injectable:
        id: id_bert_lm_collator
    collator_params:
      target_publication_key: *target_key_anchor
      tokenizer_file_path: /scratch/max/mlgym/example/bert/tokenizers/trained_wiki_tokenizer/tokenizer.json
      pad_to_multiple_of: 8
      mlm_probability: 0.15

data_loaders:
  component_type_key: DATA_LOADER
  variant_key: DEFAULT
  requirements:
    - name: iterators
      component_name: split_dataset_iterator_2
      subscription: [train_lm, train_small, val, test]
    - name: data_collator
      component_name: data_collator
  config:
    batch_size: 20
    seeds:
      train_lm: 1
      train_small: 2
      val: 3
      test: 4

model_registry:
  component_type_key: MODEL_REGISTRY
  variant_key: DEFAULT

model:
  component_type_key: MODEL
  variant_key: DEFAULT
  requirements:
    - name: model_registry
      component_name: model_registry
      subscription: lm_bert
  config:
    prediction_publication_keys:
      prediction_publication_key: *model_prediction_key_anchor

optimizer:
  component_type_key: OPTIMIZER
  variant_key: DEFAULT
  config:
    optimizer_key: ADAMW
    params:
      lr:
        sweep: absolute
        values: [5.e-5]

lr_scheduler:
  component_type_key: LR_SCHEDULER
  variant_key: DEFAULT
  config:
    lr_scheduler_key: hugging_face_scheduler
    params:
      name: linear
      num_warmup_steps: 50
      num_training_steps: 1000

loss_function_registry:
  component_type_key: LOSS_FUNCTION_REGISTRY
  variant_key: LM

metric_registry:
  component_type_key: METRIC_REGISTRY
  variant_key: DEFAULT

prediction_postprocessing_registry:
  component_type_key: PREDICTION_POSTPROCESSING_REGISTRY
  variant_key: DEFAULT

train_component:
  component_type_key: TRAIN_COMPONENT
  variant_key: ACCELERATE
  requirements:
    - name: loss_function_registry
      component_name: loss_function_registry
    - name: prediction_postprocessing_registry
      component_name: prediction_postprocessing_registry
  config:
    loss_fun_config:
      prediction_subscription_key: *model_prediction_key_anchor
      target_subscription_key: *target_key_anchor
      key: MLMCrossEntropyLoss
      tag: mlm_entropy_loss
      vocab_size: 30522

trainer:
  component_type_key: TRAINER
  variant_key: ACCELERATE
  requirements:
    - name: train_component
      component_name: train_component
    - name: model
      component_name: model
      subscription: null
    - name: data_loaders
      component_name: data_loaders
      subscription: train_lm
  config: {}

eval_component:
  component_type_key: EVAL_COMPONENT
  variant_key: ACCELERATE
  requirements:
    - name: model
      component_name: model
      subscription: null
    - name: data_loaders
      component_name: data_loaders
      subscription: [train_small, val, test]
    - name: loss_function_registry
      component_name: loss_function_registry
    - name: metric_registry
      component_name: metric_registry
    - name: prediction_postprocessing_registry
      component_name: prediction_postprocessing_registry
  config:
    cpu_target_subscription_keys:
      - *target_key_anchor
    cpu_prediction_subscription_keys: []
      # - *postprocessing_argmax_key_anchor
      # - *model_prediction_key_anchor
    # post_processors_config:
    #   - key: "ARG_MAX"
    #     prediction_subscription_key: *model_prediction_key_anchor
    #     prediction_publication_key: *postprocessing_argmax_key_anchor
    metrics_config: []
    loss_funs_config:
      - prediction_subscription_key: *model_prediction_key_anchor
        target_subscription_key: *target_key_anchor
        key: MLMCrossEntropyLoss
        tag: mlm_entropy_loss
        vocab_size: 30522

evaluator:
  component_type_key: EVALUATOR
  variant_key: ACCELERATE
  requirements:
    - name: eval_component
      component_name: eval_component

early_stopping_strategy_registry:
  component_type_key: EARLY_STOPPING_STRATEGY_REGISTRY
  variant_key: DEFAULT

early_stopping_strategy:
  component_type_key: EARLY_STOPPING_STRATEGY
  variant_key: DEFAULT
  requirements:
    - name: early_stopping_strategy_registry
      component_name: early_stopping_strategy_registry
  config:
    early_stopping_key: LAST_K_EPOCHS_IMPROVEMENT_STRATEGY
    early_stopping_config:
      min_relative_improvement: 0.00001
      epochs_window: 50
      split_name: val
      monitoring_key: "mlm_entropy_loss"
      is_increase_task: false

checkpointing_strategy_registry:
  component_type_key: CHECKPOINTING_STRATEGY_REGISTRY
  variant_key: DEFAULT

checkpointing_strategy:
  component_type_key: CHECKPOINTING_STRATEGY
  variant_key: DEFAULT
  requirements:
    - name: checkpointing_strategy_registry
      component_name: checkpointing_strategy_registry
  config:
    checkpointing_key: SAVE_LAST_EPOCH_ONLY_CHECKPOINTING_STRATEGY
